"""verl080 prefix-sharing restore end-to-end integration test.

Verifies the wiring correctness and numerical consistency of forward_step patch +
vocab_logprobs patch + restore_via_2d_unfold_verl080 in a real verl 0.8.0 + Megatron
Core 0.16.1 environment.

Automatically skipped locally (without verl/Megatron/GPU). Run in target environment
(NPU/GPU + verl080).

Test coverage:
1. **packed_index consistency**: PackedBatchLayout.packed_index matches the packed 1D
   layout actually generated by preprocess_thd_engine (including TP alignment)
2. **Restored NestedTensor satisfies no_padding_2_padding assertion**: after restoration,
   offsets reflect full [prefix|suffix] length, sequence_offsets[-1] == values.shape[0]
3. **Numerical consistency**: in PS mode, reuser's full-sequence logp/entropy matches
   baseline (independent forward without PS) within atol/rtol tolerance
"""

from __future__ import annotations

import pytest

# End-to-end tests require full verl + Megatron + GPU/NPU environment; auto-skip locally.
verl = pytest.importorskip("verl")
megatron = pytest.importorskip("megatron")
torch = pytest.importorskip("torch")

from prefix_sharing.integrations.verl_mcore import build_prefix_sharing_micro_batch_verl080
from prefix_sharing.integrations.verl_utils import restore_via_2d_unfold_verl080


# ═══════════════════════════════════════
# 1. packed_index consistency with preprocess_thd_engine
# ═══════════════════════════════════════


def test_packed_index_matches_preprocess_thd_engine():
    """Verify PackedBatchLayout.packed_index matches verl080 preprocess_thd_engine's
    packed 1D layout.

    Construct a micro-batch with prefix sharing, physically trim it, then feed it to
    preprocess_thd_engine to generate actual cu_seqlens, and compare against
    PackedBatchLayout's cu_seqlens. The provider prefix-last's provider_1d_pos must
    point to the correct logits position in the preprocess_thd_engine layout.

    Requires: real engine_self (MegatronEngineWithLMHead instance), GPU device.
    Run in CI's GPU pipeline.
    """
    # TODO: Fill in after wiring real engine fixture
    # 1. Construct batch (provider + reuser with common prefix)
    # 2. build_prefix_sharing_micro_batch_verl080 -> trimmed_batch + state
    # 3. preprocess_thd_engine(trimmed_batch["input_ids"]) -> actual_cu_seqlens
    # 4. assert state.packed_batch_layout.cu_seqlens == actual_cu_seqlens
    # 5. For each prefix-last index:
    #    assert index.provider_1d_pos == actual_cu_seqlens[provider] + prefix_len - 1
    pytest.skip("requires verl080 engine + GPU fixture")


# ═══════════════════════════════════════
# 2. Restored NestedTensor length validation
# ═══════════════════════════════════════


def test_restore_nested_tensor_satisfies_no_padding_2_padding_assert():
    """Verify restored NestedTensor satisfies no_padding_2_padding length assertion:
    sequence_offsets[-1] == values.shape[0].

    Before restore, trimmed NestedTensor length < original total length (reuser prefix
    is trimmed); after restore, full [prefix|suffix] is recovered, length == sum(original_lengths).
    """
    # TODO: Fill in after wiring real forward fixture
    # 1. forward_step(trimmed_batch) -> output_dict (NestedTensor, trimmed)
    # 2. restore_via_2d_unfold_verl080(output_dict, ...) -> restored
    # 3. assert restored["log_probs"].values().shape[0] == sum(plan.original_lengths)
    # 4. Simulate no_padding_2_padding length assertion passing
    pytest.skip("requires verl080 forward_step + GPU fixture")


# ═══════════════════════════════════════
# 3. Numerical consistency (PS vs baseline)
# ═══════════════════════════════════════


def test_ps_logprobs_match_baseline_within_tolerance():
    """In PS mode, reuser's full-sequence logp matches baseline (independent forward) numerically.

    Accuracy red line: logp/loss/gradient semantics must match baseline. KV injection lets
    the reuser's suffix segment see the provider's prefix KV, so suffix logp matches baseline;
    interior/prefix-last should also match after restore.

    Tolerance: logp atol=1e-4 (TP cross_entropy numerical precision), rtol=1e-3.
    """
    # TODO: Fill in after wiring real engine fixture
    # 1. Construct provider + reuser batch
    # 2. baseline: disable PS, independent forward for each sequence -> baseline_logp
    # 3. PS: enable PS, forward_step + restore -> ps_logp
    # 4. For reuser's full sequence:
    #    assert torch.allclose(ps_logp, baseline_logp, atol=1e-4, rtol=1e-3)
    pytest.skip("requires verl080 engine + GPU fixture")


def test_three_logprob_paths_all_restored():
    """Verify all three independent forward paths (train log_prob / old_log_prob / ref_log_prob) are correctly restored.

    The vocab_logprobs patch covers all vocab_parallel_log_probs_from_logits calls once
    installed, so all three forward paths are naturally patched. Each path's reuser prefix
    segment must be restored, otherwise KL penalty / ratio / advantage chains will have
    numerical errors.
    """
    # TODO: Fill in after wiring actor + reference policy fixture
    pytest.skip("requires actor + ref policy + GPU fixture")
